apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: server
          image: ashreesee/backend:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: "mysql-service"  # Use MySQL service name, NOT localhost
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: DB_NAME
              value: "my_new_db"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  username: cm9vdA==   # Base64 encoded "root"
  password: cXdlcnR5   # Base64 encoded "qwerty"
