# .github/workflows/backend-deploy.yml
name: Build and Push Backend Image on k8s Change

on:
  push:
    branches: [main]
    paths:
      - 'k8s/backend-deployment.yml'

env:
  DOCKERHUB_NAMESPACE: ashreesee

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Extract image tag from deployment file
      id: tag
      run: |
        IMAGE_TAG=$(grep 'image:' k8s/backend-deployment.yml | sed 's/.*://')
        echo "Using tag: $IMAGE_TAG"
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t ${{ env.DOCKERHUB_NAMESPACE }}/backend:${{ env.IMAGE_TAG }} ./backend
        docker push ${{ env.DOCKERHUB_NAMESPACE }}/backend:${{ env.IMAGE_TAG }}
