name: Backend Build & Push

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io  # or docker.io
      IMAGE_NAME: ashreesee/backend  # customize this

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set timestamp as tag
        id: set-tag
        run: echo "tag=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Build and tag Docker image
        run: |
          docker build -t $DOCKER/${{ env.IMAGE_NAME }}:${{ steps.set-tag.outputs.tag }} ./backend

      - name: Push Docker image
        run: |
          docker push $DOCKER/${{ env.IMAGE_NAME }}:${{ steps.set-tag.outputs.tag }}

      - name: Output tag
        run: |
          echo "Image tag pushed: ${{ steps.set-tag.outputs.tag }}"

