name: Build and Push Docker Image

on:
  push:
    branches: [ main ]  # or "master", depending on your repo
env:
  AWS_REGION: ap-south-1
  EKS_CLUSTER_NAME: devops
  DOCKERHUB_NAMESPACE: ashreesee
  IMAGE_TAG: latest

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Backend Image
        run: |
          docker build -t $DOCKERHUB_NAMESPACE/backend:$IMAGE_TAG ./backend
          docker push $DOCKERHUB_NAMESPACE/backend:$IMAGE_TAG