name: Build and Deploy Backend

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - 'Dockerfile'

env:
  DOCKERHUB_USERNAME: ashreesee
  IMAGE_NAME: backend
  ARGO_REPO: git@github.com:ashreesee/argo-apps-repo.git

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout App Repo
      uses: actions/checkout@v4

    - name: Generate Timestamp Tag
      id: timestamp
      run: echo "tag=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT

    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build & Push Docker Image
      run: |
        echo "Using tag: ${{ steps.timestamp.outputs.tag }}"
        docker build -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.timestamp.outputs.tag }} ./backend
        docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.timestamp.outputs.tag }}

    - name: Checkout Argo Repo
      uses: actions/checkout@v4
      with:
        repository: ashreesee/argo-apps-repo
        token: ${{ secrets.GH_TOKEN }}
        path: argo

    - name: Update Argo Manifest with New Tag
      run: |
        sed -i "s|image: ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:.*|image: ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.timestamp.outputs.tag }}|" argo/k8s/backend-deployment.yaml
        cat argo/k8s/backend-deployment.yaml  # confirm change

    - name: Commit & Push to Argo Repo
      run: |
        cd argo
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add k8s/backend-deployment.yaml
        git commit -m "Update backend image to tag ${{ steps.timestamp.outputs.tag }}"
        git push origin main
