name: Deploy Three-Tier App to AWS EKS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  EKS_CLUSTER_NAME: devops
  DOCKERHUB_NAMESPACE: ashreesee
  IMAGE_TAG: latest

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Frontend Image
        run: |
          docker build -t $DOCKERHUB_NAMESPACE/frontend:$IMAGE_TAG ./frontend
          docker push $DOCKERHUB_NAMESPACE/frontend:$IMAGE_TAG

      - name: Build and Push Backend Image
        run: |
          docker build -t $DOCKERHUB_NAMESPACE/backend:$IMAGE_TAG ./backend
          docker push $DOCKERHUB_NAMESPACE/backend:$IMAGE_TAG

  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up kubectl
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME

      - name: Deploy MySQL
        run: |
          helm upgrade --install mysql helm/mysql
          --namespace mysql \
          --create-namespace

      - name: Deploy Backend
        run: |
          helm upgrade --install backend helm/backend \
            --set image=$DOCKERHUB_NAMESPACE/backend:$IMAGE_TAG
            --namespace backend \
            --create-namespace

      - name: Deploy Frontend
        run: |
          helm upgrade --install frontend helm/frontend \
            --set image=$DOCKERHUB_NAMESPACE/frontend:$IMAGE_TAG
            --namespace frontend \
            --create-namespace